name: publish documentation
description: "Sendet generierte Doku als dispatch an zentralen Docs-Builder"

inputs:
  plugin_id:
    description: "Eindeutige Plugin-ID (Ordnername)"
    required: true

  version:
    description: "Versions-Tag (optional mit PHP-Suffix im Patchlevel)"
    required: true

  source_dir:
    description: "Pfad zur erzeugten Dokumentation"
    required: true

runs:
  using: "composite"
  steps:
    - name: Action initialized
      shell: bash
      run: |
        echo "=== Publish Docs Action ==="
        echo "Plugin ID        : ${{ inputs.plugin_id }}"
        echo "Version          : ${{ inputs.version }}"
        echo "Source dir       : ${{ inputs.source_dir }}"
        echo "==========================="

    - name: Validate inputs
      shell: bash
      run: |
        set -euo pipefail

        error() {
          echo "::error::$1"
          exit 1
        }

        # Pflichtfelder
        [ -z "${{ inputs.plugin_id }}" ]     && error "plugin_id is required and must not be empty"
        [ -z "${{ inputs.version }}" ]       && error "version is required and must not be empty"
        [ -z "${{ inputs.source_dir }}" ]    && error "source_dir is required and must not be empty"

        # source_dir muss existieren
        if [ ! -d "${{ inputs.source_dir }}" ]; then
          error "source_dir does not exist or is not a directory: ${{ inputs.source_dir }}"
        fi

        # plugin_id: nur ordnerfreundliche Zeichen
        if ! [[ "${{ inputs.plugin_id }}" =~ ^[a-zA-Z0-9._-]+$ ]]; then
          error "plugin_id contains invalid characters (allowed: a-z A-Z 0-9 . _ -)"
        fi

        # version: keine Leerzeichen, keine Slashes
        if [[ "${{ inputs.version }}" =~ [[:space:]/] ]]; then
          error "version must not contain spaces or slashes"
        fi

        echo "Input validation passed."

    - name: Normalize documentation version
      id: normalize_version
      shell: bash
      run: |
        set -euo pipefail

        RAW_VERSION="${{ inputs.version }}"

        # optionales führendes "v" entfernen (z.B. v1.2.3.4 → 1.2.3.4)
        RAW_VERSION="${RAW_VERSION#v}"

        # Fall 1: 3-Level-Version: MAJOR.MINOR.PATCH
        if [[ "$RAW_VERSION" =~ ^([0-9]+)\.([0-9]+)\.([0-9]+)$ ]]; then
          DOC_VERSION="$RAW_VERSION"

        # Fall 2 & 3: 4-Level-Version: MAJOR.MINOR.SUBMINOR.PATCH
        elif [[ "$RAW_VERSION" =~ ^([0-9]+)\.([0-9]+)\.([0-9]+)\.([0-9]+)$ ]]; then
          MAJOR="${BASH_REMATCH[1]}"
          MINOR="${BASH_REMATCH[2]}"
          SUBMINOR="${BASH_REMATCH[3]}"
          PATCH="${BASH_REMATCH[4]}"

          case "${#PATCH}" in
            1|2) DOC_PATCH="$PATCH" ;;
            3)   DOC_PATCH="${PATCH:0:1}" ;;
            *)   echo "::error::Unsupported patch length in version: $RAW_VERSION"; exit 1 ;;
          esac

          DOC_VERSION="${MAJOR}.${MINOR}.${SUBMINOR}.${DOC_PATCH}"

        else
          echo "::error::Invalid version format: $RAW_VERSION"
          exit 1
        fi

        echo "Resolved documentation version: $DOC_VERSION"
        echo "doc_version=$DOC_VERSION" >> "$GITHUB_OUTPUT"