name: publish documentation to git repository
description: "Kopiert generierte Doku versioniert in ein Repository"

inputs:
  plugin_id:
    description: "Eindeutige Plugin-ID (Ordnername)"
    required: true

  version:
    description: "Versions-Tag (optional mit PHP-Suffix im Patchlevel)"
    required: true

  source_dir:
    description: "Pfad zur erzeugten Dokumentation"
    required: true

  docs_repo:
    description: "HTTPS clone URL des Ziel-Repositories"
    required: true

  git_username:
    description: "Git Benutzername für HTTPS Authentication"
    required: true

  access_token:
    description: "Access Token mit Schreibrechten"
    required: true

  docs_branch:
    description: "Branch im Docs-Repository"
    default: "main"

  target_base_path:
    description: "Basisverzeichnis im Docs-Repo"
    default: "."

runs:
  using: "composite"
  steps:
    - name: Action initialized
      shell: bash
      run: |
        echo "=== Publish Docs Action ==="
        echo "Plugin ID        : ${{ inputs.plugin_id }}"
        echo "Version          : ${{ inputs.version }}"
        echo "Source dir       : ${{ inputs.source_dir }}"
        echo "Docs repository  : ${{ inputs.docs_repo }}"
        echo "Docs branch      : ${{ inputs.docs_branch }}"
        echo "Target base path : ${{ inputs.target_base_path }}"
        echo "==========================="

    - name: Validate inputs
      shell: bash
      run: |
        set -euo pipefail

        error() {
          echo "::error::$1"
          exit 1
        }

        # Pflichtfelder
        [ -z "${{ inputs.plugin_id }}" ]     && error "plugin_id is required and must not be empty"
        [ -z "${{ inputs.version }}" ]       && error "version is required and must not be empty"
        [ -z "${{ inputs.source_dir }}" ]    && error "source_dir is required and must not be empty"
        [ -z "${{ inputs.docs_repo }}" ]     && error "docs_repo is required and must not be empty"
        [ -z "${{ inputs.access_token }}" ]  && error "access_token is required and must not be empty"

        # source_dir muss existieren
        if [ ! -d "${{ inputs.source_dir }}" ]; then
          error "source_dir does not exist or is not a directory: ${{ inputs.source_dir }}"
        fi

        # plugin_id: nur ordnerfreundliche Zeichen
        if ! [[ "${{ inputs.plugin_id }}" =~ ^[a-zA-Z0-9._-]+$ ]]; then
          error "plugin_id contains invalid characters (allowed: a-z A-Z 0-9 . _ -)"
        fi

        # version: keine Leerzeichen, keine Slashes
        if [[ "${{ inputs.version }}" =~ [[:space:]/] ]]; then
          error "version must not contain spaces or slashes"
        fi

        echo "Input validation passed."

    - name: Normalize documentation version
      id: normalize_version
      shell: bash
      run: |
        set -euo pipefail

        RAW_VERSION="${{ inputs.version }}"

        # optionales führendes "v" entfernen (z.B. v1.2.3.4 → 1.2.3.4)
        RAW_VERSION="${RAW_VERSION#v}"

        # Fall 1: 3-Level-Version: MAJOR.MINOR.PATCH
        if [[ "$RAW_VERSION" =~ ^([0-9]+)\.([0-9]+)\.([0-9]+)$ ]]; then
          DOC_VERSION="$RAW_VERSION"

        # Fall 2 & 3: 4-Level-Version: MAJOR.MINOR.SUBMINOR.PATCH
        elif [[ "$RAW_VERSION" =~ ^([0-9]+)\.([0-9]+)\.([0-9]+)\.([0-9]+)$ ]]; then
          MAJOR="${BASH_REMATCH[1]}"
          MINOR="${BASH_REMATCH[2]}"
          SUBMINOR="${BASH_REMATCH[3]}"
          PATCH="${BASH_REMATCH[4]}"

          PATCH_LEN="${#PATCH}"

          case "$PATCH_LEN" in
          1|2)
            # normale 4-Level-Version
            DOC_PATCH="$PATCH"
            ;;
          3)
            # Composer-Sonderfall: Patch + PHP
            DOC_PATCH="${PATCH:0:1}"
            ;;
          *)
            echo "::error::Unsupported patch length (${PATCH_LEN}) in version: $RAW_VERSION"
            exit 1
            ;;
          esac

          DOC_VERSION="${MAJOR}.${MINOR}.${SUBMINOR}.${DOC_PATCH}"

        else
          echo "::error::Invalid version format: $RAW_VERSION"
          exit 1
        fi

        echo "Resolved documentation version: $DOC_VERSION"
        echo "doc_version=$DOC_VERSION" >> "$GITHUB_OUTPUT"

    - name: Clone docs repository
      shell: bash
      run: |
        set -euo pipefail

        REPO="${{ inputs.docs_repo }}"
        BRANCH="${{ inputs.docs_branch }}"
        GIT_USER="${{ inputs.git_username }}"
        TOKEN="${{ inputs.access_token }}"

        AUTH_REPO="$(echo "$REPO" | sed "s#https://#https://${GIT_USER}:${TOKEN}@#")"

        echo "::add-mask::${TOKEN}"

        git clone "$AUTH_REPO" docs-repo
        cd docs-repo

        if git ls-remote --exit-code --heads origin "$BRANCH" >/dev/null 2>&1; then
          git checkout "$BRANCH"
        else
          git checkout -b "$BRANCH"
        fi

    - name: Publish documentation
      shell: bash
      run: |
        set -euo pipefail

        PLUGIN_ID="${{ inputs.plugin_id }}"
        VERSION="${{ steps.normalize_version.outputs.doc_version }}"
        SOURCE_DIR="${{ inputs.source_dir }}"
        BASE_PATH="${{ inputs.target_base_path }}"
        BRANCH="${{ inputs.docs_branch }}"
        REPO="${{ inputs.docs_repo }}"
        GIT_USER="${{ inputs.git_username }}"
        TOKEN="${{ inputs.access_token }}"

        AUTH_REPO="$(echo "$REPO" | sed "s#https://#https://${GIT_USER}:${TOKEN}@#")"

        echo "::add-mask::${TOKEN}"

        if [ ! -d "$SOURCE_DIR" ]; then
          echo "Source dir not found: $SOURCE_DIR"
          exit 1
        fi

        TARGET_DIR="docs-repo/${BASE_PATH}/${PLUGIN_ID}/${VERSION}"

        echo "Publishing docs to $TARGET_DIR"

        rm -rf "$TARGET_DIR"
        mkdir -p "$TARGET_DIR"

        cp -R "$SOURCE_DIR"/. "$TARGET_DIR"/
        
        cd docs-repo

        git config user.name "docs-bot"
        git config user.email "docs-bot@users.noreply.github.com"

        git add .

        if git diff --cached --quiet; then
          echo "No changes to commit"
          exit 0
        fi

        git commit -m "docs(${PLUGIN_ID}): publish ${VERSION}"
        git remote set-url origin "$AUTH_REPO"
        git push -u origin "$BRANCH"