name: Build documentation

env:
  MKDOCS_CONFIG: docs/mkdocs.yml
  DOCS_OUTPUT_DIR: documentation
  ARTIFACT_NAME: documentation-html
  PLUGIN_ID: mypluginid

on:
  push:
    tags:
      - 'v*.*.*'
      - 'v*.*.*.*'
      - '*.*.*'
      - '*.*.*.*'
  workflow_dispatch:
    inputs:
      version:
        description: "Version to deploy (mandatory)"
        required: true
      deploy_docs:
        description: "Deploy documentation"
        required: false
        default: "true"

concurrency:
  group: docs-deploy
  cancel-in-progress: false

permissions:
  contents: read

jobs:
  build-docs:
    runs-on: ubuntu-latest

    outputs:
      version: ${{ steps.resolve_version.outputs.version }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Resolve version
        id: resolve_version
        shell: bash
        run: |
          set -euo pipefail

          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            VERSION="${{ github.event.inputs.version }}"
          else
            VERSION="${{ github.ref_name }}"
          fi

          if ! [[ "$VERSION" =~ ^v?[0-9]{1,3}(\.[0-9]{1,3}){2,3}$ ]]; then
            echo "::error::Invalid version format: $VERSION"
            exit 1
          fi

          if [ -z "$VERSION" ]; then
            echo "::error::Version could not be resolved"
            exit 1
          fi

          echo "Resolved version: $VERSION"
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"

      - name: Build documentation
        uses: d3datadevelopment/ci-actions/build-docs@v1.1.0
        with:
          version: ${{ steps.resolve_version.outputs.version }}
          mkdocs_config: ${{ env.MKDOCS_CONFIG }}
          output_dir: ${{ github.workspace }}/${{ env.DOCS_OUTPUT_DIR }}

      - name: Upload documentation artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: ${{ github.workspace }}/${{ env.DOCS_OUTPUT_DIR }}

  deploy-docs:
    needs: build-docs
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Download documentation artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: ${{ env.DOCS_OUTPUT_DIR }}

      - name: Deploy documentation
        if: ${{ github.event_name != 'workflow_dispatch' || github.event.inputs.deploy_docs == 'true' }}
        uses: d3datadevelopment/ci-actions/publish-docs@v1.1.0
        with:
          plugin_id: ${{ env.PLUGIN_ID }}
          version: ${{ needs.build-docs.outputs.version }}
          source_dir: ${{ env.DOCS_OUTPUT_DIR }}
          docs_repo: ${{ vars.DOCS_REPO_URL }}
          git_username: ${{ vars.DOCS_REPO_USER }}
          access_token: ${{ secrets.DOCS_REPO_TOKEN }}
