name: Build MkDocs Documentation
description: Build HTML documentation from Markdown using MkDocs Material

inputs:
  mkdocs_config:
    description: "Path to mkdocs.yml"
    required: false
    default: "mkdocs.yml"

  output_dir:
    description: "Output directory for generated HTML"
    required: false
    default: "documentation"

runs:
  using: composite
  steps:
    - name: action initialized
      run: |
        echo "=== Docs Builder Action ==="
            echo "Plugin Name      : ${{ inputs.plugin_name }}"
            echo "Version          : ${{ inputs.version }}"
            echo "Deploy enabled   : ${{ inputs.deploy }}"
            echo "==========================="
      shell: bash

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install MkDocs and Material theme
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install mkdocs mkdocs-material mkdocs-macros-plugin mkdocs-include-markdown-plugin

    - name: Build documentation
      shell: bash
      run: |
        CMD="mkdocs build --config-file '${{ inputs.mkdocs_config }}' --site-dir '${{ inputs.output_dir }}'"

        echo "Running: $CMD"
        eval "$CMD"