name: Build MkDocs Documentation
description: Build HTML documentation from Markdown using MkDocs Material

inputs:
  version:
    description: "Versions-Tag (optional mit PHP-Suffix im Patchlevel)"
    required: true

  mkdocs_config:
    description: "Path to mkdocs.yml"
    required: false
    default: "mkdocs.yml"

  output_dir:
    description: "Output directory for generated HTML"
    required: false
    default: "documentation"

runs:
  using: composite
  steps:
    - name: action initialized
      run: |
        echo "=== Docs Builder Action ==="
            echo "Plugin Name      : ${{ inputs.plugin_name }}"
            echo "Version          : ${{ inputs.version }}"
            echo "Deploy enabled   : ${{ inputs.deploy }}"
            echo "==========================="
      shell: bash

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install MkDocs and Material theme
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install mkdocs mkdocs-material mkdocs-macros-plugin mkdocs-include-markdown-plugin

    - name: Build documentation
      shell: bash
      run: |
        set -euo pipefail

        MKDOCS_CONFIG="${{ inputs.mkdocs_config }}"
        DOCS_DIR="$(dirname "$MKDOCS_CONFIG")"

        PLUGIN_VERSION="${GITHUB_REF_NAME#v}"
        PLUGIN_DATE="$(date +'%d.%m.%Y')"

        if [[ "$PLUGIN_VERSION" =~ ^(.+)\.([0-9]{3})$ ]]; then
          PLUGIN_VERSION="${BASH_REMATCH[1]}.${BASH_REMATCH[2]:0:1}"
        fi

        echo "MkDocs config : $MKDOCS_CONFIG"
        echo "Docs directory: $DOCS_DIR"
        echo "Plugin version: $PLUGIN_VERSION"
        echo "Plugin date   : $PLUGIN_DATE"

        find "$DOCS_DIR" -type f \( -name '*.md' -o -name '*.yml' \) -print0 \
          | xargs -0 sed -i \
          -e "s/__PLUGIN_VERSION__/${PLUGIN_VERSION}/g" \
          -e "s/__PLUGIN_DATE__/${PLUGIN_DATE}/g"

        CMD="mkdocs build --config-file '${{ inputs.mkdocs_config }}' --site-dir '${{ inputs.output_dir }}'"

        echo "Running: $CMD"
        eval "$CMD"

        find "${{ inputs.output_dir }}" -name 'sitemap.xml*' -delete